build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - phpcs-run --standard=PSR12
                    - php-scrutinizer-run

        tests: false
checks:
    php: true
coding_style:
    php: {  }
    
filter:
    excluded_paths:
        - '/tests/logs/*'

tools:
    php_code_sniffer:
        config:
            standard: "PSR12"
                    