name: Mutation Testing

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    name: Mutation Testing Code Review Annotations ${{ matrix.php-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: pcov
          coverage: pcov

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: |
          composer install --prefer-source --no-progress --no-suggest --no-interaction

      - name: Setup PCOV
        run: |
          composer require pcov/clobber
          vendor/bin/pcov clobber

      - name: Download Infection
        run: |
          wget https://github.com/infection/infection/releases/download/0.20.0/infection.phar
          chmod +x infection.phar

      - name: Run Infection for added files only
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          php infection.phar -j2 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered
